### ISSUE TITLE
Svelte Icons Pack

### ISSUE THREAD

**Issue by leshak** [TheComputerM/awesome-svelte#107]
Package - https://www.npmjs.com/package/svelte-icons-pack
Demo - https://leshak.github.io/svelte-icons-pack/

**Comment by polaroi8d** [comment]
You should create a PR for this resource in the [UI Components](https://github.com/TheComputerM/awesome-svelte#ui-components) > [Icons](https://github.com/TheComputerM/awesome-svelte#icons) section. IMHO.

**Comment by TheComputerM** [comment]
Added
