### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by webJose** [TheComputerM/awesome-svelte#114]
Looks like nothing is getting though anymore.

**Comment by TheComputerM** [comment]
Not really abandoned, just low maintenance, I plan to move things a bit once svelte 5 comes out.

**Comment by webJose** [comment]
I see.  Thanks for stopping by.  I made a table component that I wanted to include in your list of tables.  It is for Svelte v5 only.  Should I wait to make the PR?  Or do I do it now? Or...?

**Comment by TheComputerM** [comment]
Finally cleaned up everything, PRs welcome.
