### ISSUE TITLE
Info for adding svelte-drag?

### ISSUE THREAD

**Issue by PuruVJ** [TheComputerM/awesome-svelte#27]
Hi

I wanna add this library [svelte-drag](https://www.npmjs.com/package/svelte-drag) to this repo.

This is a single Svelte Action, about dragging. Where do I put this in the README?

Thank u

**Comment by TheComputerM** [comment]
Create a new field under utilities called 'Draggable' and put svelte-drag in it. svelte-drag looks to be a very good project with great docs. Thanks.

**Comment by PuruVJ** [comment]
Thanks!! I wanna extend this. I have another library coming svelte-resizable, and another called svelte-rnd, which combines these both. So should I have a category like "Draggable and Drop"?

**Comment by TheComputerM** [comment]
Just "Draggable" is fine.

**Comment by mateothegreat** [comment]
I linked to your neodrag repo instead (shows svelte-drag is deprecated by it).
Thanks!
