### ISSUE TITLE
▦ PowerTable (Inspired by DataTables, Powered by Svelte)

### ISSUE THREAD

**Issue by muonw-public** [TheComputerM/awesome-svelte#56]
Suggestion for your 🕶️ list:

# [▦](https://muonw.github.io/powertable/) PowerTable

PowerTable is a JavaScript component that turns JSON data into an interactive HTML table. This facilitates manual inspection, sorting, filtering, searching, and editing of the data. 

[![MuonW PowerTable](https://github.com/muonw/powertable/raw/main/src/data/muonw_powertable_830x448.png)](https://muonw.github.io/powertable/examples/example1)

## ✨ Features

- No runtime dependencies
- Sorting (single- and multi-column)
- Filtering (per column and global. RegEx)
- Inline editing
- Re-arrangeable layout segments
- Optional styling
- Custom parsing per column
- Usable as Svelte component or ES module

Repository: https://github.com/muonw/powertable
Demos: https://muonw.github.io/powertable

**Comment by TheComputerM** [comment]
Nice, open a PR and I will merge it.
