### ISSUE TITLE
svg2svelte

### ISSUE THREAD

**Issue by derektata** [TheComputerM/awesome-svelte#60]
# [svg2svelte](https://github.com/derektata/svg2svelte-rs)

Easily turn an SVG file into a Svelte Component, Rewritten in Rust 🦀 

`svg2svelte` parses the svg file's ids for `bind:` in the name and converts them into variables we can manipulate later on with an animation library (e.g. [anime.js](https://animejs.com/))

It's capable of creating Javascript or Typescript components. (see below)
I wasn't sure where you would like me to add this. `Dev Tools > Other Tools` seems like it would be a good place for it.

![Screen Shot 2022-08-25 at 12 34 22 PM](https://user-images.githubusercontent.com/63433989/186720886-fb90db22-b815-440f-b28b-8622c1b82f83.png)

**Comment by TheComputerM** [comment]
> Research if the stuff you're including is actually awesome. Only put stuff on the list that you or another contributor can personally recommend. You should rather leave stuff out than include too much. - Awesome list

Your project is certainly useful, but I think it falls into too much of a niche category for most of the people to find it useful.
