### ISSUE TITLE
Performance Category

### ISSUE THREAD

**Issue by LeeviOlander** [TheComputerM/awesome-svelte#7]
Performance is a key factor that is taken into account when choosing a frontend framework. A key question that is often asked regarding Svelte is: "Does Svelte scale?", which refers to the compilation model of Svelte.

This is why is suggest that a category for performance should be added. 

For example, the question  "Does Svelte scale?" has been answered at least here:
[SvelteScaling](https://svelte-scaling.acmion.com) 
[svelte-it-will-scale](https://github.com/halfnelson/svelte-it-will-scale)

**Comment by TheComputerM** [comment]
Done, create a superset called "Studies".
