### ISSUE TITLE
add Skeleton ui toolkit to UI libraries

### ISSUE THREAD

**Issue by poinck** [TheComputerM/awesome-svelte#87]
Please see this pull-request to add the awesome Skeleton ui toolkit to the list: https://github.com/TheComputerM/awesome-svelte/pull/86

The list of UI libraries does contain some abandoned ui toolkits. I like to add Skeleton to the list, because it is actively maintained and really awesome. I am using Skeleton for some days now and sure that my future project will make use of it. In my opinion, it could move up the UI libraries list a bit. If you think so, too, I can adapt my pull-request accordingly.

**Comment by TheComputerM** [comment]
That's fine, I also plan to add a *not maintained* tag to the entries.

**Comment by TheComputerM** [comment]
Closing as PR is merged
