### ISSUE TITLE
Add "svelte-document", a Svelte framework for building documents (PDFs) in Svelte.

### ISSUE THREAD

**Issue by mblouka** [TheComputerM/awesome-svelte#99]
I was actually looking for a tool like this a month or so ago when designing posters. I know React has [react-pdf](https://github.com/diegomura/react-pdf) for making PDF files, but I was not able to find an equivalent for Svelte. I did a small amount of research on how web technologies and stylesheets interact with printing, which resulted in [this little project](https://github.com/mblouka/jamaat-caiposters), but it isn't portable.

To fill in this need for other people as well, and to provide Svelte's answer to react-pdf, I wrote a more general tool for making PDFs/resumes/presentations with Svelte called [`svelte-document`](https://github.com/mblouka/svelte-document) ([npm](https://www.npmjs.com/package/svelte-document)), which is a zero configuration[^1] cli tool which takes Svelte files in a directory, compiles them, bundles them and outputs a neat PDF file. Supports mostly everything you would think: fonts, assets (images), stylesheets, importing Svelte components, etc. The tool itself is very simple in usage: install the package globally (`npm install -g svelte-document`), then run it in the root containing your Svelte files (`svelte-document`). There's no need to initialize a Node package with any dependencies (but you can do so if you want).

It also includes similar semantics to SvelteKit for some special files, e.g. the `+layout.svelte` file is used to wrap the contents of each and every page.

Even though it is already very usable, I want to expand its functionality in the near future with things such as first-class support for PostCSS (so people can use plugins such as TailwindCSS and Sass), a plugin mechanism, and additional options in the configuration (maybe for setting a root folder for Svelte files, for instance).

[^1]: Of course, additional configuration can be provided in a `document.config.json` file to specify things such as page dimensions, page orientation, and compilation/bundle parameters, if needed.

**Comment by TheComputerM** [comment]
Closing as PR is merged.
